---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.4.0
  hooks:
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: detect-private-key
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=*]
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-added-large-files
    - id: check-json
    - id: pretty-format-json
      args:
        - autofix
    - id: check-merge-conflict
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    # - id: no-commit-to-branch
# - repo: https://github.com/igorshubovych/markdownlint-cli
#  rev: v0.30.0
#  hooks:
#    - id: markdownlint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.32.0
  hooks:
    - id: yamllint
      name: yamllint
      description: This hook runs yamllint
      entry: yamllint
      language: python
      types: [file, yaml]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terrascan
      args:
        - --args=--severity MEDIUM
        - --args=-i terraform
        - --args=-t azure
        - --args=-d ./
    - id: terraform_tflint
    - id: terraform_tfsec
    # - id: terraform_checkov
